spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/twitter_like_app
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoint:
    health:
      show-details: always
