@startuml twitter-like-er-diagram

entity "roles" {
    + id INT AUTO_INCREMENT
    --
    name VARCHAR(255) [NN]
    created_at TIMESTAMP [NN]
    updated_at TIMESTAMP [NN]
    deleted_at TIMESTAMP
}
entity "users" {
    + id INT AUTO_INCREMENT
    --
    login_id VARCHAR(255) [NN][UQ]
    password VARCHAR(255) [NN]
    name VARCHAR(255)
    created_at TIMESTAMP [NN]
    updated_at TIMESTAMP [NN]
    deleted_at TIMESTAMP
    --
    role_id INT [FK]
}

entity "tweets" {
    + id BIGINT AUTO_INCREMENT
    --
    message TEXT
    created_at TIMESTAMP [NN]
    updated_at TIMESTAMP [NN]
    deleted_at TIMESTAMP
    --
    user_id INT [FK]
}
entity "favs" {
    + id INT AUTO_INCREMENT
    --
    created_at TIMESTAMP [NN]
    updated_at TIMESTAMP [NN]
    deleted_at TIMESTAMP
    --
    user_id INT [FK]
    tweet_id BIGINT [FK]
}

roles ||-ri-o{ users
users ||-ri-o{ tweets
tweets ||-do-o{ favs
users ||-o{ favs

@enduml
